services:
  - type: web
    name: inspiredbynature-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: inspiredbynature-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inspiredbynature-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: inspiredbynature-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: inspiredbynature-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inspiredbynature-db
          property: password

databases:
  - name: inspiredbynature-db
    plan: free
    databaseName: inspiredbynature
    region: ohio
